version: '3.8'

services:  
  server:
    image: 'nginx:stable-alpine'
    ports:
      - '8000:80'
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  php:
    build: 
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated ##delegated é um comando para falar que o source code não precisa ser instantaniamente atualizado
    # ports:
    #   - '3000:9000'
    # NÃO PRECISA POR CONTA QUE JÁ VAI EXISTIR A CONEXÃO DEFAULT CRIADA E O ARQUIVO NGINX.CONF CONSEGUE ACESSAR A PORTA INTERNA PELO NOME DO SERVIÇO E ESTAR NA MSM CONN

  mysql:
    image: 'mysql:5.7'
    env_file:
      - ./env/mysql.env

  composer:
    build: 
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html

  npm:
    image: 'node:14'
    working_dir: /var/www/html
    entrypoint: [ "npm" ]
    volumes:
      - ./src:/var/www/html

  artisan:
    build: 
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint:  [ "php", "/var/www/html/artisan" ] #override caso exista algum no Dockerfile & substitui o comando run também.


    