apiVersion: v1
kind: Service
metadata:
  name: second-service
spec:
  selector: ## Quais recursos devem ser controlados por esse recurso
    app: second-app ## Mesma característica do POD e o mesmo valor.
  ports:
    - protocol: 'TCP'
      port: 80 ## Qualquer porta que vc deseja.
      targetPort: 8080 ## Porta do container.
  type: NodePort
  


