apiVersion: v1
kind: Service # Responsável por expor os PODS para requisições de fora ou de outros PODS dentro do cluster.
metadata: 
  name: task-service
spec:
  selector:
    app: task
  ports:
    - protocol: "TCP"
      port: 8000
      targetPort: 8000
  type: LoadBalancer