apiVersion: v1
kind: Service # Responsável por expor os PODS para requisições de fora ou de outros PODS dentro do cluster.
metadata: 
  name: users-service
spec:
  selector:
    app: users
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: LoadBalancer